<?php $this->headScript()->prependFile($this->basePath() . '/js/jquery.print.js')?>


<form method="get" action="" class="form-inline">
<div class="row">
  <div class="col-xs-2">
    <input name="month" class="date-picker" type="text" placeholder="Month of report" value="<?=(isset($_GET['month'])?$_GET['month']:"")?>"/>
  </div>
  <div class="col-xs-2">
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="button" id="print" class="btn btn-primary">Print</button>
    </div>
</div>





</form>
<br />
<div class="printable">
<span style="font-size:10px;">INVESTORS ASSURANCE CORPORATION<br />
_____LEGAZPI_____ - BDU or Business Center<br />
COLLECTION REPORT FOR THE MONTH OF <?=$month->format('F Y')?><br />
<br />
<strong>BONDS / FIRE / PA / MARINE & OTHER CASUALITY</strong></span>
<table class="table table-striped table-hover">
	<thead>
	<tr bgcolor="#666">
    	<td style="color:white">No</td>
        <td style="color:white">Name</td>
        <td style="color:white">Date Issued</td>
        
        <td align="center" style="color:white">Basic Premium</td>
        <td align="center" style="color:white">DST</td>
        <td align="center" style="color:white">EVAT</td>
        <td align="center" style="color:white">LGT</td>
        <td align="right" style="color:white">Total Amount Due</td>
    </tr>
    </thead>
    <?php if(!count($list)) : ?>
    <tr>
    	<td colspan="8" align="center"><span class="label label-warning">No result</span></td>
    </tr>
    <?php endif; ?>
    <tbody>
<?php
	$total = 0;
	$premiumpaid = 0;
	$lgt = 0;
	$vat = 0;
	$stamps = 0;
	foreach($list as $entry) : 
		$total = $total + $entry->getTotalamountdue();
		$premiumpaid = $premiumpaid + $entry->getPremiumpaid();
		$lgt = $lgt + $entry->getLgt();
		$vat = $vat + $entry->getVat();
		$stamps = $stamps + $entry->getStamps();
?>
	<tr>
    	<td><?=$entry->getNo()?></td>
        <td><?=$entry->getName()?></td>
        
        <td><?=$entry->getDateissued()?></td>
        
        
        <td align="center"><?=$entry->getPremiumpaid()?></td>
        <td align="center"><?=$entry->getStamps()?></td>
        <td align="center"><?=$entry->getVat()?></td>
        <td align="center"><?=$entry->getLgt()?></td>
        <td align="right">&#8369; <?=$entry->getTotalamountdue()?></td>
    </tr>
<?php endforeach; ?>
	<tr>
    	<td></td>
        <td></td>
        <td></td>
        <td align="center">&#8369; <?=$premiumpaid?></td>
        <td align="center">&#8369; <?=$stamps?></td>
        <td align="center">&#8369; <?=$vat?></td>
        <td align="center">&#8369; <?=$lgt?></td>
        
        <td align="right"><span class="label label-info">Total</span> &#8369; <?=$total?></td>
    </tr>
	</tbody>
</table>
<div class="row">
  <div class="col-md-6">
  Prepared by:
  </div>
  <div class="col-md-6">
  <span class="pull-right">Attested by:</span>
  </div>
</div>

</div>
<script type="text/javascript">
$(function() {
    options = {
		pattern: 'yyyy-mm', // Default is 'mm/yyyy' and separator char is not mandatory
		selectedYear: 2014,
		startYear: 2008,
		finalYear: 2014,
		monthNames: ['Jan', 'Feb', 'Mar', 'Apr', 'Mar', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
	};
	
	$('.date-picker').monthpicker(options);
	
	$("#print").click(function(e){e.preventDefault();	$(".printable").print()});
});
</script>