<div class="row">
	<div class="col-xs-12 col-sm-4 col-sm-offset-4 shadow">
    	<a href="<?=$this->url('profiling/action',array('action' => 'certificateofcover'))?>"><span class="btn btn-success fileinput-button btn-lg btn-block">
            
            <span>Profiling</span>
            <i class="glyphicon glyphicon-user"></i>
        </span></a>
        <br />
        <a href="<?=$this->url('monitoring')?>"><span class="btn btn-success fileinput-button btn-lg btn-block">
            
            <span>Monitoring</span>
            <i class="glyphicon glyphicon-search"></i>
        </span></a>
        <br />
        <a href="<?=$this->url('report')?>"><span class="btn btn-success fileinput-button btn-lg btn-block">
            <span>Report</span>
            <i class="glyphicon glyphicon-file"></i>
        </span></a>
    </div>
</div>