<?php $this->headScript()->prependFile($this->basePath() . '/js/jquery.print.js')?>
<form method="get" action="" class="form-inline">
<div class="row">
  <div class="col-xs-2">
    <input class="form-control" type="text" id="start" name="start" placeholder="Starting date" value="<?=(isset($_GET['start'])?$_GET['start']:"")?>"/>
  </div>
  <div class="col-xs-2">
    <input class="form-control" type="text" id="end" name="end" placeholder="Ending date" value="<?=(isset($_GET['end'])?$_GET['end']:"")?>"/>
  </div>
  <div class="col-xs-2">
    <button type="submit" class="btn btn-primary">Submit</button>
    <button id="print" class="btn btn-primary">Print</button>
    </div>
</div>





</form>
<br />
<div class="printable">
<?php 
$start = new \DateTime($start);
$end = new \DateTime($end);
?>
<?=$start->format('F j, Y')?> - <?=$end->format('F j, Y')?>
<table class="table table-striped table-hover">
	<thead>
	<tr bgcolor="#666">
    	<td style="color:white">No</td>
        <td style="color:white">Name</td>
        <td style="color:white">Isap</td>
        <td style="color:white">Date Issued</td>
        <td style="color:white">End of Insurance</td>
        <td align="right" style="color:white">Total Amount Due</td>
    </tr>
    </thead>
    <?php if(!count($list)) : ?>
    <tr>
    	<td colspan="6" align="center"><span class="label label-warning">No result</span></td>
    </tr>
    <?php endif; ?>
    <tbody>
<?php
	$total = 0; 
	foreach($list as $entry) : 
		$total = $total + $entry->getTotalamountdue();
?>
	<tr>
    	<td><?=$entry->getNo()?></td>
        <td><?=$entry->getName()?></td>
        <td><?=$entry->getIsap()?></td>
        <td><?=$entry->getDateissued()?></td>
        <td><?=$entry->getEndofinsurance()->format('Y-m-d')?></td>
        <td align="right">&#8369; <?=$entry->getTotalamountdue()?></td>
    </tr>
<?php endforeach; ?>
	<tr>
    	<td colspan="5"><p>The total no of insured vehicle from <?=$start->format('F j, Y')?> to <?=$end->format('F j, Y')?> 
        is <span class="badge"><?=count($list)?></span></p>
        
        <blockquote>
          <footer>Note - By means of this system it automatically generate or calculate the insured vehicle.</footer>
        </blockquote>
        </td><td align="right"><span class="label label-info">Total</span> &#8369; <?=$total?></td>
    </tr>
	</tbody>
</table>

</div>
<script type="text/javascript">
$("#start").datepicker({dateFormat:'yy-mm-dd',changeMonth: true,changeYear: true});
$("#end").datepicker({dateFormat:'yy-mm-dd',changeMonth: true,changeYear: true});
$("#print").click(function(){	$(".printable").print()});
</script>