<div class="row">
	<div class="col-md-4 col-md-offset-4">
        <div class="list-group">
          <a href="<?=$this->url('monitoring/action',array('action' => 'calculate-insured-vehicle'))?>" class="list-group-item">Calculate Insured Vehicles</a>
          <a href="#" class="list-group-item">Check Insurance Expiration</a>
          <a href="<?=$this->url('profiling/action',array('action' => 'claim-settings'))?>" class="list-group-item">Claim Settings</a>
        </div>

	</div>
</div>